#!/usr/bin/env python3
# Generates a One Piece Jolly Roger skull bitmap for the MNT Reform 2 keyboard OLED (128x32).
# Output: C arrays for skull frames (eyes-off and eyes-on) in SSD1306 page format.
# SSD1306 format: bitmap[page*128 + col], bit 0 = top row of page, bit 7 = bottom.

import math

W, H = 128, 32
NUM_FRAMES = 2  # eyes-dark, eyes-lit

def make_bitmap():
    return [[0]*W for _ in range(H)]

def pset(bm, x, y, v=1):
    if 0 <= x < W and 0 <= y < H:
        bm[y][x] = v

def hline(bm, x1, x2, y, v=1):
    for x in range(x1, x2+1):
        pset(bm, x, y, v)

def vline(bm, x, y1, y2, v=1):
    for y in range(y1, y2+1):
        pset(bm, x, y, v)

def ellipse_fill(bm, cx, cy, rx, ry, v=1):
    for dy in range(-ry-1, ry+2):
        for dx in range(-rx-1, rx+2):
            if rx > 0 and ry > 0:
                if (dx/rx)**2 + (dy/ry)**2 <= 1.0:
                    pset(bm, cx+dx, cy+dy, v)

def ellipse_outline(bm, cx, cy, rx, ry, v=1):
    steps = max(rx, ry) * 8
    for i in range(steps):
        angle = 2 * math.pi * i / steps
        x = round(cx + rx * math.cos(angle))
        y = round(cy + ry * math.sin(angle))
        pset(bm, x, y, v)

def thick_line(bm, x1, y1, x2, y2, thickness=2, v=1):
    dx = x2 - x1
    dy = y2 - y1
    length = max(abs(dx), abs(dy), 1)
    # perpendicular direction
    px = -dy / math.sqrt(dx*dx + dy*dy + 1e-9)
    py = dx / math.sqrt(dx*dx + dy*dy + 1e-9)
    for i in range(length+1):
        cx = x1 + dx * i // length
        cy = y1 + dy * i // length
        for t in range(-(thickness//2), thickness//2 + 1):
            pset(bm, round(cx + px*t), round(cy + py*t), v)

def circle_fill(bm, cx, cy, r, v=1):
    ellipse_fill(bm, cx, cy, r, r, v)

def to_oled(bm):
    result = [0] * (4 * W)
    for page in range(4):
        for col in range(W):
            byte = 0
            for bit in range(8):
                row = page * 8 + bit
                if bm[row][col]:
                    byte |= (1 << bit)
            result[page * W + col] = byte
    return result

def draw_skull(bm, eyes_lit=False):
    # ---- CROSSBONES (drawn first, skull covers the center) ----
    # All pixels kept inside 3px margin: cols 3..124, rows 3..28
    bx1, bx2 = 10, 118
    bone_top_y = 5
    bone_bot_y = 27

    # Bone 1: top-left to bottom-right
    thick_line(bm, bx1, bone_top_y, bx2, bone_bot_y, thickness=3)
    # Bone 2: bottom-left to top-right
    thick_line(bm, bx1, bone_bot_y, bx2, bone_top_y, thickness=3)

    # Knobs at the 4 ends (radius=3 stays within margin)
    circle_fill(bm, bx1, bone_top_y, 3)
    circle_fill(bm, bx2, bone_bot_y, 3)
    circle_fill(bm, bx1, bone_bot_y, 3)
    circle_fill(bm, bx2, bone_top_y, 3)

    # ---- SKULL HEAD (filled ellipse, ~3px margin from display edges) ----
    skull_cx, skull_cy = 64, 13
    skull_rx, skull_ry = 16, 10
    ellipse_fill(bm, skull_cx, skull_cy, skull_rx, skull_ry)

    # ---- JAW (rectangle below skull) ----
    jaw_x1, jaw_x2 = 53, 75
    jaw_y1, jaw_y2 = 20, 27
    for y in range(jaw_y1, jaw_y2+1):
        hline(bm, jaw_x1, jaw_x2, y)

    # ---- EYE SOCKETS (carved out) ----
    eye_rx, eye_ry = 4, 3
    left_eye_cx, right_eye_cx = 55, 73
    eye_cy = 12
    ellipse_fill(bm, left_eye_cx, eye_cy, eye_rx, eye_ry, v=0)
    ellipse_fill(bm, right_eye_cx, eye_cy, eye_rx, eye_ry, v=0)

    # Lit eyes: fill the sockets back (glowing)
    if eyes_lit:
        ellipse_fill(bm, left_eye_cx, eye_cy, eye_rx-2, eye_ry-1, v=1)
        ellipse_fill(bm, right_eye_cx, eye_cy, eye_rx-2, eye_ry-1, v=1)

    # ---- NOSE HOLE (tiny oval) ----
    ellipse_fill(bm, skull_cx, 17, 2, 1, v=0)

    # ---- TEETH (4 teeth with gaps) ----
    # Jaw x=53..75 = 23px. 4 teeth of 4px + 3 gaps of 1px = 19px. Centered: start=55
    for i in range(4):
        tx = 55 + i * 5
        for y in range(23, 28):
            hline(bm, tx, tx+3, y)
        if i < 3:
            for y in range(23, 28):
                pset(bm, tx+4, y, 0)

def print_preview(bm, label):
    print(f"// {label} (128x32 preview):")
    for row in range(H):
        line = "// "
        for col in range(W):
            line += "#" if bm[row][col] else "."
        print(line)
    print()

def print_c_array(oled_data, name):
    print(f"const uint8_t {name}[512] PROGMEM = {{")
    for i in range(0, 512, 16):
        chunk = oled_data[i:i+16]
        print("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    print("};")
    print()

# Frame 0: eyes dark (classic Jolly Roger)
bm0 = make_bitmap()
draw_skull(bm0, eyes_lit=False)

# Frame 1: eyes lit (glowing)
bm1 = make_bitmap()
draw_skull(bm1, eyes_lit=True)

oled0 = to_oled(bm0)
oled1 = to_oled(bm1)

print("/*")
print("  One Piece Jolly Roger skull for MNT Reform 2 keyboard OLED (128x32).")
print("  Generated by gen_skull.py")
print("  SPDX-License-Identifier: MIT")
print("*/")
print()
print("#include <avr/pgmspace.h>")
print()

print_c_array(oled0, "skull_dark")
print_c_array(oled1, "skull_lit")

print_preview(bm0, "skull_dark")
print_preview(bm1, "skull_lit")
