/*
  MNT Reform 2.0 Keyboard Firmware
  See keyboard.c for Copyright
  SPDX-License-Identifier: MIT
*/

#include "keyboard.h"

#ifdef KBD_SWP_CTRL
  #define R4_C1 HID_KEYBOARD_SC_EXECUTE
  #define R6_C1 HID_KEYBOARD_SC_LEFT_CONTROL
#else
  #define R4_C1 HID_KEYBOARD_SC_LEFT_CONTROL
  #define R6_C1 HID_KEYBOARD_SC_EXECUTE
#endif

// Fourth row
#define MATRIX3_DEFAULT_ROW_4 \
  R4_C1,\
  KEY_A,\
  KEY_S,\
  KEY_D,\
  KEY_F,\
  KEY_G,\
  KEY_H,\
  KEY_J,\
  KEY_K,\
  KEY_L,\
  KEY_SEMICOLON_AND_COLON,\
  KEY_APOSTROPHE_AND_QUOTE,\
  KEY_ENTER,\
  KEY_ENTER

// Sixth row
#define MATRIX3_DEFAULT_ROW_6 \
  R6_C1,\
  HID_KEYBOARD_SC_LEFT_GUI,\
  HID_KEYBOARD_SC_LEFT_ALT,\
  KEY_SPACE,\
  KEY_SPACE,\
  KEY_SPACE,\
  KEY_SPACE,\
  HID_KEYBOARD_SC_RIGHT_ALT,\
  HID_KEYBOARD_SC_RIGHT_CONTROL,\
  HID_KEYBOARD_SC_LEFT_ARROW,\
  HID_KEYBOARD_SC_DOWN_ARROW,\
  HID_KEYBOARD_SC_RIGHT_ARROW

// Every line of `matrix` is a row of the keyboard, starting from the top.
// Check keyboard.h for the definitions of the default rows.
uint8_t matrix[KBD_MATRIX_SZ] = {
  MATRIX_DEFAULT_ROW_1,
  MATRIX_DEFAULT_ROW_2,
  MATRIX_DEFAULT_ROW_3,
  MATRIX3_DEFAULT_ROW_4,
  MATRIX_DEFAULT_ROW_5,
  MATRIX3_DEFAULT_ROW_6,

  // Marker for layout editor (FIXME)
  KBD_EDITOR_MARKER
};

// When holding down HYPER
uint8_t matrix_fn[KBD_MATRIX_SZ] = {
  // Media keys on Hyper + F7-F12
  KEY_ESCAPE,
  HID_KEYBOARD_SC_MEDIA_BRIGHTNESS_DOWN,
  HID_KEYBOARD_SC_MEDIA_BRIGHTNESS_UP,
  KEY_F3,
  KEY_F4,
  KEY_F5,
  KEY_F6,
  HID_KEYBOARD_SC_MEDIA_PREVIOUS_TRACK,
  HID_KEYBOARD_SC_MEDIA_PLAY,
  HID_KEYBOARD_SC_MEDIA_NEXT_TRACK,
  HID_KEYBOARD_SC_MEDIA_MUTE,
  HID_KEYBOARD_SC_MEDIA_VOLUME_DOWN,
  HID_KEYBOARD_SC_MEDIA_VOLUME_UP,
  KEY_CIRCLE,

  KEY_GRAVE_ACCENT_AND_TILDE,
  KEY_1,
  KEY_2,
  KEY_3,
  KEY_4,
  KEY_5,
  KEY_6,
  KEY_7,
  KEY_8,
  KEY_9,
  KEY_0,
  KEY_MINUS_AND_UNDERSCORE,
  KEY_EQUAL_AND_PLUS,
  KEY_DELETE,

  MATRIX_DEFAULT_ROW_3,
  MATRIX3_DEFAULT_ROW_4,

  HID_KEYBOARD_SC_LEFT_SHIFT,
  HID_KEYBOARD_SC_NON_US_BACKSLASH_AND_PIPE,
  KEY_Z,
  KEY_X,
  KEY_C,
  KEY_V,
  KEY_B,
  KEY_N,
  KEY_M,
  HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN,
  HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN,
  KEY_SLASH_AND_QUESTION_MARK,
  HID_KEYBOARD_SC_PAGE_UP,
  HID_KEYBOARD_SC_RIGHT_SHIFT,

  R6_C1,
  HID_KEYBOARD_SC_LEFT_GUI,
  HID_KEYBOARD_SC_LEFT_ALT,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  HID_KEYBOARD_SC_RIGHT_ALT,
  HID_KEYBOARD_SC_RIGHT_CONTROL,
  HID_KEYBOARD_SC_HOME,
  HID_KEYBOARD_SC_PAGE_DOWN,
  HID_KEYBOARD_SC_END
};

// Second layer (toggled by HYPER+CIRCLE)
uint8_t matrix_fn_toggled[KBD_MATRIX_SZ] = {
  // Custom top row
  KEY_ESCAPE,
  HID_KEYBOARD_SC_MEDIA_BRIGHTNESS_DOWN,
  HID_KEYBOARD_SC_MEDIA_BRIGHTNESS_UP,
  KEY_F3,
  KEY_F4,
  KEY_F5,
  KEY_F6,
  HID_KEYBOARD_SC_MEDIA_PREVIOUS_TRACK,
  HID_KEYBOARD_SC_MEDIA_PLAY,
  HID_KEYBOARD_SC_MEDIA_NEXT_TRACK,
  HID_KEYBOARD_SC_MEDIA_MUTE,
  HID_KEYBOARD_SC_MEDIA_VOLUME_DOWN,
  HID_KEYBOARD_SC_MEDIA_VOLUME_UP,
  KEY_CIRCLE,

  MATRIX_DEFAULT_ROW_2,
  MATRIX_DEFAULT_ROW_3,
  MATRIX3_DEFAULT_ROW_4,
  MATRIX_DEFAULT_ROW_5,
  MATRIX3_DEFAULT_ROW_6
};
